# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('painel', '0003_auto_20170829_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registro')),
                ('status', models.BooleanField(default=True, verbose_name='Ativar Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativar Projeto'),
        ),
    ]
