# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_auto_20170901_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacao',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativar Informação'),
        ),
    ]
