# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_informacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacao',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
    ]
