# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_auto_20170901_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacao',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço'),
        ),
    ]
