# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_auto_20170901_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacao',
            name='lat',
            field=models.CharField(blank=True, max_length=200, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='informacao',
            name='lng',
            field=models.CharField(blank=True, max_length=200, verbose_name='Longitude'),
        ),
    ]
