# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('painel', '0009_auto_20170901_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('status', models.BooleanField(default=True, verbose_name='Ativar Produto')),
                ('tipo', models.CharField(choices=[('Aquarismo', 'Aquarismo'), ('Lago Ornamental', 'Lago Ornamental'), ('Camping', 'Camping'), ('Arqueria e Tiro esportivo', 'Arqueria e Tiro esportivo'), ('Mergulho', 'Mergulho'), ('Pesca esportiva', 'Pesca esportiva')], max_length=25)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
