version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aquariomaniacos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ltn-i&$wvde=nn@8$vj3y%l(_s^s@156+%+q1nkafx7$lq1*u*
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: aquariomaniacos
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres