# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
    ]
